export const DASHBOARD_REQUEST_START = 'DASHBOARD_REQUEST_START' as const

export const DASHBOARD_REQUEST_SUCCESS = 'DASHBOARD_REQUEST_SUCCESS' as const

export const DASHBOARD_REQUEST_FAILURE = 'DASHBOARD_REQUEST_FAILURE' as const